controllers/stellplatz.py
from flask import Blueprint, request, render_template, flash
import sqlalchemy
from werkzeug.utils import redirect

from Forms.add.stellplatz import AddStellplatz
from Forms.delete.stellplatz import DeleteStellplatz
from Forms.edit.stellplatz import EditStellplatz
from model.models import db, Stellplatz

stellplatz_blueprint = Blueprint('stellplatz_blueprint', __name__)


@stellplatz_blueprint.route("/stellplatz", methods=["GET", "POST"])
def stellplatz():
    session: sqlalchemy.orm.scoping.scoped_session = db.session

    page = request.args.get('page', 1, type=int)
    stellplaetze = session.query(Stellplatz).order_by(Stellplatz.StellplatzId).paginate(
        page, 10, error_out=False)

    return render_template("/stellplatz/stellplatz.html", stellplaetze=stellplaetze)


@stellplatz_blueprint.route("/stellplatz/stellplatz_add", methods=["GET", "POST"])
def stellplatz_add():
    session: sqlalchemy.orm.scoping.scoped_session = db.session
    add_stellplatz_form = AddStellplatz()

    if request.method == 'POST':
        if add_stellplatz_form.validate_on_submit():
            new_stellplatz = Stellplatz()

            new_stellplatz.KategorieId = add_stellplatz_form.KategorieId.data
            new_stellplatz.Qualitaet = add_stellplatz_form.Qualitaet.data
            new_stellplatz.Laenge = add_stellplatz_form.Laenge.data
            new_stellplatz.Breite = add_stellplatz_form.Breite.data
            db.session.add(new_stellplatz)
            db.session.commit()

            try:
                db.session.add(new_stellplatz)
                db.session.commit()
            except:
                add_stellplatz_form = AddStellplatz()
                return render_template("/stellplatz/stellplatz_add.html", form=add_stellplatz_form)

            return redirect("/stellplatz")
        else:
            return render_template("stellplatz/stellplatz_add.html", form=add_stellplatz_form)
    else:
        return render_template("stellplatz/stellplatz_add.html", form=add_stellplatz_form)


@stellplatz_blueprint.route("/stellplatz/stellplatz_edit", methods=["GET", "POST"])
def stellplatz_edit():
    session: sqlalchemy.orm.scoping.scoped_session = db.session

    edit_stellplatz_form = EditStellplatz()

    StellplatzId = request.args["StellplatzId"]

    stellplatz_to_edit = session.query(Stellplatz).filter(
        Stellplatz.StellplatzId == StellplatzId).first()

    if request.method == "POST":
        if edit_stellplatz_form.validate_on_submit():
            StellplatzId = edit_stellplatz_form.StellplatzId.data
            stellplatz_to_edit = db.session.query(Stellplatz).filter(
                Stellplatz.StellplatzId == StellplatzId).first()

            stellplatz_to_edit.KategorieId = edit_stellplatz_form.KategorieId.data
            stellplatz_to_edit.Qualitaet = edit_stellplatz_form.Qualitaet.data
            stellplatz_to_edit.Laenge = edit_stellplatz_form.Laenge.data
            stellplatz_to_edit.Breite = edit_stellplatz_form.Breite.data
            stellplatz_to_edit.Hoehe = edit_stellplatz_form.Hoehe.data

            db.session.commit()
        return redirect("/stellplatz")
    else:
        edit_stellplatz_form.StellplatzId.data = stellplatz_to_edit.StellplatzId
        edit_stellplatz_form.KategorieId.data = stellplatz_to_edit.KategorieId
        edit_stellplatz_form.Qualitaet.data = stellplatz_to_edit.Qualitaet
        edit_stellplatz_form.Laenge.data = stellplatz_to_edit.Laenge
        edit_stellplatz_form.Breite.data = stellplatz_to_edit.Breite
        edit_stellplatz_form.Hoehe.data = stellplatz_to_edit.Hoehe

        return render_template("stellplatz/stellplatz_edit.html", form=edit_stellplatz_form)


@stellplatz_blueprint.route("/stellplatz/delete_stellplatz", methods=["GET", "POST"])
def stellplatz_delete():
    delete_stellplatz_form = DeleteStellplatz()
    if delete_stellplatz_form.validate_on_submit():
        StellplatzId = delete_stellplatz_form.StellplatzId.data
        stellplatz_to_delete = db.session.query(Stellplatz).filter(
            Stellplatz.StellplatzId == StellplatzId)
        stellplatz_to_delete.delete()
        db.session.commit()
    return redirect("/stellplatz")

templates/stellplatz/stellplatz.html
{%extends 'base.html'%}

{%block body%}


<table class="table">
    <thead>
    <tr>
        <th scope="col">KategorieId</th>
        <th scope="col">Qualitaet</th>
        <th scope="col">Laenge</th>
        <th scope="col">Breite</th>
        <th scope="col">Höhe</th>

    </tr>
    </thead>
    <tbody>

    {% for stellplatz in stellplaetze.items %}
    <tr>
        <td>{{stellplatz.KategorieId}}</td>
        <td>{{stellplatz.Qualitaet}}</td>
        <td>{{stellplatz.Laenge}}</td>
        <td>{{stellplatz.Breite}}</td>
        <td>{{stellplatz.Hoehe}}</td>
        <td>
            <a class="btn btn-success" href="/stellplatz/stellplatz_edit?StellplatzId={{stellplatz.StellplatzId}}">✏️</a>
            <form action="/stellplatz/delete_stellplatz" method="post" style="display: inline;">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="StellplatzId" id="StellplatzId" value="{{stellplatz.StellplatzId}}">
                <button class="btn btn-danger" onclick="delete_stellplatz(this); return false;">🗑️</button>

            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<div id="data-navigation">
    <a href="{{ url_for('stellplatz_blueprint.stellplatz', page=1) }}"
       class="btn btn-outline-secondary
           {% if stellplaetze.page == 1 %}disabled{% endif %}">
        &laquo;&laquo;
    </a>
    <a href="{{ url_for('stellplatz_blueprint.stellplatz', page=stellplaetze.prev_num) }}"
       class="btn btn-outline-secondary
           {% if stellplaetze.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
    <a class="btn btn-secondary">
        {{ stellplaetze.page }}
    </a>

    <a href="{{ url_for('stellplatz_blueprint.stellplatz', page=stellplaetze.next_num) }}"
       class="btn btn-outline-secondary
           {% if stellplaetze.page == stellplaetze.pages or stellplaetze.pages == 0 %}disabled{% endif %}">
        &raquo;
    </a>
    <a href="{{ url_for('stellplatz_blueprint.stellplatz', page=stellplaetze.pages) }}"
       class="btn btn-outline-secondary
           {% if stellplaetze.page == stellplaetze.pages or stellplaetze.pages == 0%}disabled{% endif %}">
        &raquo;&raquo;
    </a>
</div>



{%endblock%}

templates/stellplatz/stellplatz_edit.html
{%extends 'base.html'%}

{%block body%}

<form method="post">
    {{form.csrf_token}}

    <!-- {{ form.errors }} -->

    <div class="mb-3">
        <label for="StellplatzId" class="form-label"></label>
        {{form.StellplatzId(class_="form-control",readonly=True)}}
    </div>

    <div class="mb-3">
        <label for="KategorieId" class="form-label">KategorieId</label>
        {{form.KategorieId(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Qualitaet" class="form-label">Qualitaet</label>
        {{form.Qualitaet(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Laenge" class="form-label">Laenge</label>
        {{form.Laenge(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Breite" class="form-label">Breite</label>
        {{form.Breite(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Hoehe" class="form-label">Höhe</label>
        {{form.Hoehe(class_="form-control")}}
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{%endblock%}