controllers/kategorie.py
from flask import Blueprint, request, render_template, flash
import sqlalchemy
from werkzeug.utils import redirect

from Forms.add.kategorie import AddKategorie
from Forms.delete.kategorie import DeleteKategorie
from Forms.edit.kategorie import EditKategorie
from model.models import db, Kategorie

kategorie_blueprint = Blueprint('kategorie_blueprint', __name__)


@kategorie_blueprint.route("/kategorie", methods=["GET", "POST"])
def kategorie():
    session: sqlalchemy.orm.scoping.scoped_session = db.session

    page = request.args.get('page', 1, type=int)
    kategories = session.query(Kategorie).order_by(Kategorie.KategorieId).paginate(
        page, 10, error_out=False)

    return render_template("/kategorie/kategorie.html", kategories=kategories)


@kategorie_blueprint.route("/kategorie/kategorie_add", methods=["GET", "POST"])
def kategorie_add():
    session: sqlalchemy.orm.scoping.scoped_session = db.session
    add_kategorie_form = AddKategorie()

    if request.method == 'POST':
        if add_kategorie_form.validate_on_submit():
            new_kategorie = Kategorie()

            new_kategorie.Kategoriename = add_kategorie_form.Kategoriename.data
            new_kategorie.Preis = add_kategorie_form.Preis.data
            new_kategorie.Videoueberwachung = add_kategorie_form.Videoueberwachung.data
            new_kategorie.Versicherung = add_kategorie_form.Versicherung.data
            new_kategorie.Farbe = add_kategorie_form.Farbe.data

            try:
                db.session.add(new_kategorie)
                db.session.commit()
            except:
                flash("An Exception is raised")
                add_kategorie_form = AddKategorie()
                return render_template("/kategorie/kategorie_add.html", form=add_kategorie_form)

            return redirect("/kategorie")
        else:
            return render_template("kategorie/kategorie_add.html", form=add_kategorie_form)
    else:
        return render_template("kategorie/kategorie_add.html", form=add_kategorie_form)


@kategorie_blueprint.route("/kategorie/kategorie_edit", methods=["GET", "POST"])
def kategories_edit():
    session: sqlalchemy.orm.scoping.scoped_session = db.session

    edit_kategorie_form = EditKategorie()

    KategorieId = request.args["KategorieId"]

    kategorie_to_edit = session.query(Kategorie).filter(
        Kategorie.KategorieId == KategorieId).first()

    if request.method == "POST":
        if edit_kategorie_form.validate_on_submit():
            KategorieId = edit_kategorie_form.KategorieId.data
            kategorie_to_edit = db.session.query(Kategorie).filter(
                Kategorie.KategorieId == KategorieId).first()

            kategorie_to_edit.Kategoriename = edit_kategorie_form.Kategoriename.data
            kategorie_to_edit.Preis = edit_kategorie_form.Preis.data
            kategorie_to_edit.Videoueberwachung = edit_kategorie_form.Videoueberwachung.data
            kategorie_to_edit.Versicherung = edit_kategorie_form.Versicherung.data
            kategorie_to_edit.Farbe = edit_kategorie_form.Farbe.data
            db.session.commit()
        return redirect("/kategorie")
    else:
        edit_kategorie_form.KategorieId.data = kategorie_to_edit.KategorieId
        edit_kategorie_form.Kategoriename.data = kategorie_to_edit.Kategoriename
        edit_kategorie_form.Preis.data = kategorie_to_edit.Preis
        edit_kategorie_form.Videoueberwachung.data = kategorie_to_edit.Videoueberwachung
        edit_kategorie_form.Versicherung.data = kategorie_to_edit.Versicherung
        edit_kategorie_form.Farbe.data = kategorie_to_edit.Farbe

        return render_template("kategorie/kategorie_edit.html", form=edit_kategorie_form)


@kategorie_blueprint.route("/kategorie/delete_kategorie", methods=["GET", "POST"])
def kategories_delete():
    delete_kategorie_form = DeleteKategorie()
    if delete_kategorie_form.validate_on_submit():
        KategorieId = delete_kategorie_form.KategorieId.data
        kategorie_to_delete = db.session.query(Kategorie).filter(
            Kategorie.KategorieId == KategorieId)
        kategorie_to_delete.delete()
        db.session.commit()
    return redirect("/kategorie")

templates/kategorie/kategorie.html
{%extends 'base.html'%}

{%block body%}


<table class="table">
    <thead>
    <tr>
        <th scope="col">Kategoriename</th>
        <th scope="col">Preis</th>
        <th scope="col">Videoueberwachung</th>
        <th scope="col">Versicherung</th>
        <th scope="col">Farbe</th>

    </tr>
    </thead>
    <tbody>

    {% for kategorie in kategories.items %}
    <tr>
        <td>{{kategorie.Kategoriename}}</td>
        <td>{{kategorie.Preis}}</td>
        <td>{{kategorie.Videoueberwachung}}</td>
        <td>{{kategorie.Versicherung}}</td>
        <td>{{kategorie.Farbe}}</td>
        <td>
            <a class="btn btn-success" href="/kategorie/kategorie_edit?KategorieId={{kategorie.KategorieId}}">✏️</a>
            <form action="/kategorie/delete_kategorie" method="post" style="display: inline;">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="KategorieId" id="KategorieId" value="{{kategorie.KategorieId}}">
                <button class="btn btn-danger" onclick="delete_auto(this); return false;">🗑️</button>

            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<div id="data-navigation">
    <a href="{{ url_for('kategorie_blueprint.kategorie', page=1) }}"
       class="btn btn-outline-secondary
           {% if kategories.page == 1 %}disabled{% endif %}">
        &laquo;&laquo;
    </a>
    <a href="{{ url_for('kategorie_blueprint.kategorie', page=kategories.prev_num) }}"
       class="btn btn-outline-secondary
           {% if kategories.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
    <a class="btn btn-secondary">
        {{ kategories.page }}
    </a>

    <a href="{{ url_for('kategorie_blueprint.kategorie', page=kategories.next_num) }}"
       class="btn btn-outline-secondary
           {% if kategories.page == kategories.pages or kategories.pages == 0 %}disabled{% endif %}">
        &raquo;
    </a>
    <a href="{{ url_for('kategorie_blueprint.kategorie', page=kategories.pages) }}"
       class="btn btn-outline-secondary
           {% if kategories.page == kategories.pages or kategories.pages == 0%}disabled{% endif %}">
        &raquo;&raquo;
    </a>
</div>



{%endblock%}

templates/kategorie/kategorie_add.html
{%extends 'base.html'%}

{%block body%}

<form method="post">
    {{form.csrf_token}}

    <!-- {{ form.errors }} -->

    <div class="mb-3">
        <label for="Kategoriename" class="form-label">Kategoriename</label>
        {{form.Kategoriename(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Preis" class="form-label">Preis</label>
        {{form.Preis(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Videoueberwachung" class="form-label">Videoueberwachung</label>
        {{form.Videoueberwachung(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Versicherung" class="form-label">Versicherung</label>
        {{form.Versicherung(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Farbe" class="form-label">Farbe</label>
        {{form.Farbe(class_="form-control")}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{%endblock%}

templates/kategorie/kategorie_edit.html
{%extends 'base.html'%}

{%block body%}

<form method="post">
    {{form.csrf_token}}

    <!-- {{ form.errors }} -->

    <div class="mb-3">
        <label for="KategorieId" class="form-label"></label>
        {{form.KategorieId(class_="form-control",readonly=True)}}
    </div>

    <div class="mb-3">
        <label for="Kategoriename" class="form-label">Kategoriename</label>
        {{form.Kategoriename(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Preis" class="form-label">Preis</label>
        {{form.Preis(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Videoueberwachung" class="form-label">Videoueberwachung</label>
        {{form.Videoueberwachung(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Versicherung" class="form-label">Versicherung</label>
        {{form.Versicherung(class_="form-control")}}
    </div>

    <div class="mb-3">
        <label for="Farbe" class="form-label">Farbe</label>
        {{form.Farbe(class_="form-control")}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{%endblock%}